# Generated by Django 4.2.11 on 2024-08-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
    ]
