# Generated by Django 4.2.11 on 2024-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='content',
        ),
        migrations.AddField(
            model_name='snippet',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
