# Generated by Django 4.2.11 on 2024-09-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_at',
        ),
        migrations.AddField(
            model_name='snippet',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='snippets.snippet'),
        ),
    ]
